export const LOGIN_REQUEST = '@user/LOGIN_REQUEST';
export const LOGIN_SUCCESS = '@user/LOGIN_SUCCESS';
export const LOGIN_FAILURE = '@user/LOGIN_FAILURE';

export const FIREBASE_LOGIN_REQUEST = '@user/FIREBASE_LOGIN_REQUEST';
export const FIREBASE_LOGIN_SUCCESS = '@user/FIREBASE_LOGIN_SUCCESS';
export const FIREBASE_LOGIN_FAILURE = '@user/FIREBASE_LOGIN_FAILURE';
export const USER_DATA_RETRIEVED = '@user/USER_DATA_RETRIEVED';

export const REQUEST_QUERY_STRING_LOGIN = '@user/REQUEST_QUERY_STRING_LOGIN';
export const QUERY_STRING_LOGIN_SUCCESS = '@user/QUERY_STRING_LOGIN_SUCCESS';
export const QUERY_STRING_LOGIN_FAILURE = '@user/QUERY_STRING_LOGIN_FAILURE';

export const IMAGE_UPLOAD_REQUEST = '@user/IMAGE_UPLOAD_REQUEST';
export const IMAGE_UPLOAD_SUCCESS = '@user/IMAGE_UPLOAD_SUCCESS';
export const IMAGE_UPLOAD_FAILURE = '@user/IMAGE_UPLOAD_FAILURE';
