export const PRODUCT_REQUEST = '@product/PRODUCT_REQUEST';
export const PRODUCT_SUCCESS = '@product/PRODUCT_SUCCESS';
export const PRODUCT_FAILURE = '@product/PRODUCT_FAILURE';

export const SAVE_USER_PAYMENT_REQUEST = '@product/SAVE_USER_PAYMENT_REQUEST';
export const SAVE_USER_PAYMENT_SUCCESS = '@product/SAVE_USER_PAYMENT_SUCCESS';
export const SAVE_USER_PAYMENT_FAILURE = '@product/SAVE_USER_PAYMENT_FAILURE';
